import "./globals.css";
import type { Metadata } from "next";
import { Inter, Outfit, Raleway } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import NavBar from "@/components/NavBar";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={raleway.className}>
          <NavBar/>
          {children}
          </body>
      </html>
    </ClerkProvider>
  );
}
